frontend improvements
adshares/ads-operator-panel pull request #115
Opened 2018-10-18 09:42 UTC by Meskat

- decreased header size
- created icon cell components
- swapped type, direction, status cells with proper icons
- combined messages and transactions count columns on smaller screens
- removed public key column on mobile screens
-removed block_id and message on the mobile screen in the transactions table
-formatted date with moment js (time column)
-used zebra styled rows in tables
- remove scale effect on hover on mobiles (used darker bg on hover for readability)
- created tests for icon cells components

2018-10-22 08:24 UTC, c3zi requested changes

2018-10-22 08:25 UTC, c3zi requested changes
Please check

2018-10-22 08:52 UTC, Meskat commented on package.json
> +      "!app/components/**/Button.js",
cause it's not tested yet (and probably even doesn't need to cause its pack of styled components) and it broked tests coverage

2018-10-22 08:55 UTC, Meskat commented on app/components/molecules/Table/IconCells/StatusTableCell.js
> +  ]).isRequired,
I've tried it but I've got an error ` Failed prop type: Invalid prop `value` of type `object` supplied to `StatusTableCell`, expected `number`.`

2018-10-22 08:56 UTC, Meskat commented on package.json
> +      "!app/containers/TransactionsListPage/index.js",
coverage

2018-10-22 08:56 UTC, Meskat commented on app/components/molecules/Table/IconCells/StatusTableCell.js
> +  ]).isRequired,
I've tried it but I've got an error ` Failed prop type: Invalid prop `value` of type `object` supplied to `StatusTableCell`, expected `number`.`

2018-10-23 09:05 UTC, c3zi approved these changes

2018-10-24 06:08 UTC, merged